import { expectType } from 'tsd';
import CalHeatmap from '../src/CalHeatmap';
const cal = new CalHeatmap();
expectType(cal);
expectType(cal.paint());
expectType(cal.paint({}));
expectType(cal.paint({ range: 3 }));
expectType(cal.paint({}, []));
expectType(cal.next());
expectType(cal.next(1));
expectType(cal.previous());
expectType(cal.previous(1));
expectType(cal.jumpTo(new Date()));
expectType(cal.fill());
expectType(cal.fill(''));
expectType(cal.fill([]));
expectType(cal.destroy());
expectType(cal.dimensions());
expectType(cal.on('eventName', () => { }));
expectType(cal.addTemplates({}));
expectType(cal.extendDayjs(() => () => { }));
